// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbOQDJmiZJNo8qJMEMeGCXgzuZsnIoCbo',
    appId: '1:545565443284:web:d7d3d1357cc8c7c54e2741',
    messagingSenderId: '545565443284',
    projectId: 'dalel-f30d6',
    authDomain: 'dalel-f30d6.firebaseapp.com',
    storageBucket: 'dalel-f30d6.appspot.com',
    measurementId: 'G-G5PD4RQWHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyP8ATo7QeZLooeDn3HPa-2YgFWfHBznM',
    appId: '1:545565443284:android:545993d8eee3e0a84e2741',
    messagingSenderId: '545565443284',
    projectId: 'dalel-f30d6',
    storageBucket: 'dalel-f30d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs8nQIvuViV0HneDIRp_etCthK5_0prJs',
    appId: '1:545565443284:ios:9a5517c79399a7a54e2741',
    messagingSenderId: '545565443284',
    projectId: 'dalel-f30d6',
    storageBucket: 'dalel-f30d6.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs8nQIvuViV0HneDIRp_etCthK5_0prJs',
    appId: '1:545565443284:ios:9a5517c79399a7a54e2741',
    messagingSenderId: '545565443284',
    projectId: 'dalel-f30d6',
    storageBucket: 'dalel-f30d6.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbOQDJmiZJNo8qJMEMeGCXgzuZsnIoCbo',
    appId: '1:545565443284:web:5747053cd3e39f854e2741',
    messagingSenderId: '545565443284',
    projectId: 'dalel-f30d6',
    authDomain: 'dalel-f30d6.firebaseapp.com',
    storageBucket: 'dalel-f30d6.appspot.com',
    measurementId: 'G-ZN87HKPJES',
  );
}
